// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCT3sxot031nD2BokwSeUD4kNdmm6Nkp9g',
    appId: '1:619740870481:android:c1720fb715d338a0900570',
    messagingSenderId: '619740870481',
    projectId: 'momocard-e107f',
    databaseURL: 'https://momocard-e107f-default-rtdb.firebaseio.com',
    storageBucket: 'momocard-e107f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB0L1BB0q_xHz7kJwhoF5WMUwpJxt56h_E',
    appId: '1:619740870481:ios:9f979d902fca4ec7900570',
    messagingSenderId: '619740870481',
    projectId: 'momocard-e107f',
    databaseURL: 'https://momocard-e107f-default-rtdb.firebaseio.com',
    storageBucket: 'momocard-e107f.appspot.com',
    androidClientId: '619740870481-hhpsoa4ni1sb9abagusj81e2v9636a49.apps.googleusercontent.com',
    iosClientId: '619740870481-3i153r2jermm8auvthm8c7ee5lddnfgh.apps.googleusercontent.com',
    iosBundleId: 'com.sixamtech.6amMartDelivery',
  );
}
